### ISSUE TITLE
Velocity won't start - CleanScreenshare 1.5.3

### ISSUE THREAD

**Issue by KimDinestin** [frafol/CleanScreenShare#1]
Velocity won't start and throus an error when using CleanScreenshare
(this problem present itslef from cleanss version 1.5.0, it works normally in the versions befor that one)

Error: https://prnt.sc/IyY5VAd8dTWr

**Comment by frafol** [comment]
I will solve it tomorrow morning, for now you can start it by inserting the LimboAPI plugin in your server
