### ISSUE TITLE
Velocity "use_disconnect_instead_of_fallback" - CleanScreenShare 2.0.2

### ISSUE THREAD

**Issue by KimDinestin** [frafol/CleanScreenShare#11]
use_disconnect_instead_of_fallback doesn't work, if in the fallback_servers list there's one server that is incorrect or doesn't exist it throws an error and wont' end the screenshare, so it doesn't actually kick the player as this option says and it doesn't ignore the fallback_servers list
[even if a server in that list is correct it will not end the control and will not send the player to that server]
https://prnt.sc/sOLZx0708wCm
https://prnt.sc/E8BHr1P21Mm5

- the plugin is present in the control server

**Comment by frafol** [comment]
checking now

**Comment by frafol** [comment]
can you send a video at the end of a control?

**Comment by frafol** [comment]
[cleanscreenshare-2.0.3.zip](https://github.com/frafol/CleanScreenShare/files/12647505/cleanscreenshare-2.0.3.zip)
Hi, try to use this.

**Comment by KimDinestin** [comment]
the command /ssfinish now doesn't do anything, doesn't throw any errors or warns in console and does not get the player off the control state.
so the player and the staff member will remain in control until both of them leave the server.


besides that, the kick actually doesn't work, if the control manages to end the kick doesn't work, it throws this error (https://prnt.sc/bRimiquak8jg)
but the velocity config has that server configured, if i manually kick the player from the control server with /minecraft:kick it returns the player in the lobby

**Comment by frafol** [comment]
can you send me spigot.yml & server.propreties of the control server?

**Comment by KimDinestin** [comment]
spigot.yml > https://pastebin.com/Q7mqJf7Y
server.properties > https://pastebin.com/DiWQ91YQ

**Comment by frafol** [comment]
seems that servers do not communicate, is admin/suspect spawn working correctly?

**Comment by frafol** [comment]
closing for no response.
